# server:
#   servlet:
#     context-path: /api

# app:
#   datasource:
#     jdbc-url: jdbc:postgresql://localhost:5432/postgresdemo
#     username: postgres
#     password: 'helloworld123'
#     pool-size: 30  